services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: propel
    ports:
      - "5433:5432"  # expuesto en el host como 5433 para evitar conflictos con pg local
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d propel"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/propel
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

volumes:
  pg_data:
